# Game settings
ICON = 'Assets/Images/icon.bmp'
TITLE = 'Rider'
FPS = 60
WIDTH = 900
HEIGHT = 900

ZOOM = .6
ZOOM_VARIABILITY = 0.2
ZOOM_MIN = ZOOM - ZOOM_VARIABILITY
ZOOM_DECAY = .002
ZOOM_INCREASE = .001
DISPLACEMENT = (150*(1-ZOOM), 700*(1-ZOOM))
# World settings
GRAVITY = (0, 0.5)
DEBUG = False
# DEBUG = True
CAMERA_INITIAL_POSITION = (150, 700)

SHAKE = 4

LOADING_IMAGE = 'Assets/Images/loading.png'

SIMPLE_COIN_POSITION = 834, 27
