BLUE = 'Assets/Textures/Blue.jpg'
GROUND = 'Assets/Textures/ground.png'
GRASS = 'Assets/Textures/grass.png'
WOOD = 'Assets/Textures/wood.png'
SOIL = 'Assets/Textures/soil2.png'
GRASS_2 = 'Assets/Textures/grass2.png'
